# Fly.io configuration for Regime Compass

app = "regimecompass"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[machine]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 2

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

# Database configuration
[[services]]
  protocol = "tcp"
  internal_port = 5432
  processes = ["db"]

# Redis configuration (optional)
[[services]]
  protocol = "tcp"
  internal_port = 6379
  processes = ["redis"]

# Volume for persistent data
[[mounts]]
  source = "regimecompass_data"
  destination = "/app/data"

# Environment variables (set via fly secrets)
# fly secrets set DATABASE_URL="postgresql://..."
# fly secrets set POLYGON_API_KEY="..."
# fly secrets set TRADIER_API_KEY="..."
# fly secrets set JWT_SECRET="..."