# Fly.io configuration for RegimeCompass Next.js App
app = "regimecompass"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[machine]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 2

[[mounts]]
  source = "regimecompass_data"
  destination = "/app/data"