# Fly.io configuration for RegimeCompass Next.js App

app = "regimecompass"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[machine]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 2

# Volume for persistent data
[[mounts]]
  source = "regimecompass_data"
  destination = "/app/data"

# Environment variables (set via fly secrets)
# fly secrets set POSTGRES_HOST="..."
# fly secrets set POSTGRES_PASSWORD="..."
# fly secrets set JWT_SECRET="..."
# fly secrets set ENCRYPTION_KEY="..."