apiVersion: v1
kind: ConfigMap
metadata:
  name: gamma-adaptive-config
  namespace: gamma-adaptive
  labels:
    app: gamma-adaptive
    component: config
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  CONFIG_PATH: "/app/gamma-adaptive-config.json"
  
  # Database configuration
  POSTGRES_DB: "gamma_adaptive_prod"
  POSTGRES_USER: "gamma_prod"
  POSTGRES_PORT: "5432"
  
  # Redis configuration
  REDIS_PORT: "6379"
  
  # Feature flags
  PAPER_TRADING_ENABLED: "true"
  LIVE_TRADING_ENABLED: "false"
  DASHBOARD_ENABLED: "true"
  API_ENABLED: "true"
  MONITORING_ENABLED: "true"
  
  # Security settings
  RATE_LIMIT_ENABLED: "true"
  CORS_ORIGIN: "https://gamma-adaptive.com"
  SSL_ENABLED: "true"
  SECURITY_HEADERS_ENABLED: "true"
  AUDIT_LOGGING_ENABLED: "true"
  
  # Performance settings
  MAX_CONCURRENT_OPERATIONS: "100"
  PROCESSING_TIMEOUT: "30000"
  MEMORY_THRESHOLD: "0.8"
  CPU_THRESHOLD: "0.8"
  
  # Health check settings
  HEALTH_CHECK_HOST: "localhost"
  DATABASE_HEALTH_CHECK: "true"
  REDIS_HEALTH_CHECK: "true"
  EXTERNAL_API_HEALTH_CHECK: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gamma-adaptive-app-config
  namespace: gamma-adaptive
  labels:
    app: gamma-adaptive
    component: app-config
data:
  gamma-adaptive-config.json: |
    {
      "version": "1.0.0",
      "environment": "production",
      "lastModified": "2024-01-01T00:00:00.000Z",
      "orchestrator": {
        "watchlist": ["SPY", "QQQ", "AAPL", "MSFT", "NVDA", "TSLA", "META", "AMZN", "GOOGL", "NFLX"],
        "maxConcurrentTrades": 3,
        "confidenceThreshold": 0.62,
        "fibZoneBlocklist": ["EXHAUSTION"],
        "updateInterval": 30000,
        "priorityWeights": {
          "SPY": 1.0,
          "QQQ": 0.9,
          "AAPL": 0.8,
          "MSFT": 0.8,
          "NVDA": 0.7
        },
        "cooldownPeriod": 300000,
        "maxTickersPerWorker": 5
      },
      "signalProcessing": {
        "weights": {
          "trendComposite": 0.25,
          "momentumDivergence": 0.20,
          "volumeProfile": 0.20,
          "ribbonAlignment": 0.15,
          "fibConfluence": 0.10,
          "gammaExposure": 0.10
        },
        "thresholds": {
          "minConfidence": 0.5,
          "maxConfidence": 0.95,
          "convictionMultiplier": 1.2,
          "regimeAdjustment": 0.1
        },
        "adjustments": {
          "regimeWeights": {
            "BULL_MARKET": 1.1,
            "BEAR_MARKET": 0.9,
            "SIDEWAYS": 1.0,
            "HIGH_VOLATILITY": 0.8,
            "LOW_VOLATILITY": 1.0
          },
          "volatilityAdjustments": {
            "LOW": 1.0,
            "MEDIUM": 0.9,
            "HIGH": 0.8,
            "EXTREME": 0.6
          },
          "timeOfDayMultipliers": {
            "MARKET_OPEN": 1.2,
            "MID_DAY": 1.0,
            "MARKET_CLOSE": 1.1,
            "AFTER_HOURS": 0.5
          }
        },
        "caching": {
          "enabled": true,
          "ttlMinutes": 5,
          "maxCacheSize": 1000
        }
      },
      "riskManagement": {
        "positionSizing": {
          "maxRiskPerTrade": 0.02,
          "maxPortfolioHeat": 0.20,
          "maxDrawdown": 0.05,
          "confidenceMultipliers": {
            "high": 1.2,
            "medium": 1.0,
            "low": 0.8
          },
          "fibZoneMultipliers": {
            "COMPRESSION": "1.2",
            "MID_EXPANSION": "1.0",
            "FULL_EXPANSION": "0.8",
            "OVER_EXTENSION": "0.4",
            "EXHAUSTION": "0.0"
          },
          "regimeAdjustments": {
            "BULL_MARKET": "1.1",
            "BEAR_MARKET": "0.8",
            "SIDEWAYS": "0.9",
            "HIGH_VOLATILITY": "0.7",
            "LOW_VOLATILITY": "1.0"
          },
          "vixAdjustments": {
            "low": 1.0,
            "medium": 0.8,
            "high": 0.5
          }
        },
        "limits": {
          "maxConsecutiveLosses": 2,
          "maxDailyLoss": 0.03,
          "vixThreshold": 30,
          "emergencyStopLoss": 0.10
        },
        "drawdownProtection": {
          "maxDrawdownThreshold": 0.05,
          "defensiveModeThreshold": 0.04,
          "recoveryThreshold": 0.02,
          "positionReductionFactor": 0.5,
          "defensiveModeMultiplier": 0.3
        },
        "marketRiskAdjustments": {
          "fibZoneMultipliers": {
            "COMPRESSION": "1.2",
            "MID_EXPANSION": "1.0",
            "FULL_EXPANSION": "0.8",
            "OVER_EXTENSION": "0.4",
            "EXHAUSTION": "0.0"
          },
          "vixThresholds": {
            "low": 15,
            "medium": 25,
            "high": 35,
            "extreme": 50
          },
          "vixMultipliers": {
            "low": 1.0,
            "medium": 0.8,
            "high": 0.5,
            "extreme": 0.2
          },
          "regimeMultipliers": {
            "BULL_MARKET": "1.1",
            "BEAR_MARKET": "0.7",
            "SIDEWAYS": "0.9",
            "HIGH_VOLATILITY": "0.6",
            "LOW_VOLATILITY": "1.0"
          },
          "emergencyOverrides": {
            "enabled": true,
            "maxReduction": 0.1,
            "triggerConditions": [
              "VIX > 50",
              "SPY daily change > 5%",
              "Put/Call ratio > 2.0"
            ]
          }
        }
      },
      "dataProviders": {
        "primary": {
          "name": "Polygon.io",
          "apiKey": "PLACEHOLDER",
          "baseUrl": "https://api.polygon.io",
          "rateLimit": 100,
          "timeout": 5000
        },
        "fallback": {
          "name": "TwelveData",
          "apiKey": "PLACEHOLDER",
          "baseUrl": "https://api.twelvedata.com",
          "rateLimit": 60,
          "timeout": 5000
        },
        "options": {
          "name": "Tradier",
          "apiKey": "PLACEHOLDER",
          "baseUrl": "https://api.tradier.com",
          "rateLimit": 120
        },
        "vix": {
          "name": "CBOE",
          "apiKey": "PLACEHOLDER",
          "baseUrl": "https://api.cboe.com",
          "updateInterval": 60000
        }
      },
      "logging": {
        "level": "info",
        "enableConsole": true,
        "enableFile": true,
        "filePath": "./logs/gamma-adaptive.log",
        "maxFileSize": "10MB",
        "maxFiles": 5,
        "enableStructuredLogging": true,
        "correlationIds": true
      },
      "performance": {
        "maxConcurrentOperations": 50,
        "processingTimeout": 30000,
        "memoryThreshold": 0.8,
        "cpuThreshold": 0.8,
        "healthCheckInterval": 30000,
        "metricsCollection": {
          "enabled": true,
          "interval": 60000,
          "retention": 86400000
        }
      },
      "features": {
        "paperTradingEnabled": true,
        "liveTradingEnabled": false,
        "learningSystemEnabled": true,
        "dashboardEnabled": true,
        "alertsEnabled": true,
        "backtestingEnabled": true,
        "apiEnabled": true
      }
    }