apiVersion: v1
kind: ConfigMap
metadata:
  name: regimecompass-config
  namespace: regimecompass
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"
  # Database configuration
  DB_CONNECTION_POOL_SIZE: "20"
  DB_MAX_CONNECTIONS: "50"
  DB_IDLE_TIMEOUT: "30000"
  DB_CONNECTION_TIMEOUT: "10000"
  # Rate limiting
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX: "1000"
  API_RATE_LIMIT_MAX: "1000"
  AUTH_RATE_LIMIT_MAX: "10"
  TRADING_RATE_LIMIT_MAX: "10"
  # Security
  CORS_ORIGINS: "https://regimecompass.com,https://www.regimecompass.com"
  TRUSTED_PROXIES: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
  # Trading configuration
  DEFAULT_ACCOUNT_BALANCE: "100000"
  MAX_RISK_PER_TRADE: "0.02"
  MAX_PORTFOLIO_HEAT: "0.20"
  # Monitoring
  ENABLE_AUDIT_LOGGING: "true"
  AUDIT_LOG_LEVEL: "standard"
  AUDIT_LOG_RETENTION_DAYS: "90"
