apiVersion: v1
kind: ServiceAccount
metadata:
  name: regimecompass-sa
  namespace: regimecompass
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: regimecompass
  name: regimecompass-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: regimecompass-rolebinding
  namespace: regimecompass
subjects:
- kind: ServiceAccount
  name: regimecompass-sa
  namespace: regimecompass
roleRef:
  kind: Role
  name: regimecompass-role
  apiGroup: rbac.authorization.k8s.io
